name: Shared UI semantic release CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'Release:')"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Validate code
        run: npm run validate

      - name: Build code
        run: npm run build

      - name: Publish semantic version
        run: cd dist && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - uses: actions/checkout@v3
        with:
          ref: develop
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Prepare develop with version bump
        run: |
          git config --global user.email "admin@kaunostudija.lt"
          git config --global user.name "System"
          npm run prepare:patch
          git push
